version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: cb_db
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
  api:
    image: apicb
    depends_on:
      - mongodb
    build: 
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002

  ui:
    image: cb_ui
    depends_on:
      - api
    build:
      context: Ui
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173

volumes:
  mongo_volume: